sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml.dist tests
after_success:
  - travis_retry php vendor/bin/php-coveralls -v -x coverage/logs/clover.xml -o coverage/logs/coveralls-upload.json
