matrix:
  include:
    - language: php
      php: nightly
      install:
        - composer self-update --2
        - composer update --ignore-platform-req=php
    - language: php
      php: 7.4
    - language: php
      php: 7.3
    - language: php
      php: 7.2
    - language: php
      php: 7.1

cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - ./vendor/bin/phpcs src
  - ./vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml.dist tests
after_success:
  - travis_retry php vendor/bin/php-coveralls -v -x coverage/logs/clover.xml -o coverage/logs/coveralls-upload.json
