name: WebThumbnailer CI
on: [push]
jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, xml, curl
          tools: composer:v2
          coverage: xdebug

      - name: Check PHP version
        run: php -v

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Run linter
        run: ./vendor/bin/phpcs

      - name: Run tests
        run: |
          ./vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration phpunit.xml.dist tests

      - name: Upload coverage results to Coveralls
        if: ${{ matrix.php-versions == '8.0' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vendor/bin/php-coveralls --coverage_clover=coverage/logs/clover.xml --json_path=coverage/logs/coveralls-upload.json -v

      # https://github.com/marketplace/actions/setup-php-action#cache-composer-dependencies
